# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Yacp
version:      2.00
version_from: lib/Config/Yacp.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Fcntl:                         0
    Object::InsideOut:             0
    Parse::RecDescent:             0
    Test::Harness:                 0
    Test::More:                    0
    Test::Pod:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
